import streamlit as st
import google.generativeai as genai
import PyPDF2
import io

# Set page config
st.set_page_config(
    page_title="Research Paper Analyzer",
    layout="wide"
)

# Hardcoded Gemini API key
api_key = "AIzaSyDrksJ5fvEXs7ZCKS4qQ4-LFgP8M4MZAE0"

# Configure Gemini API
genai.configure(api_key=api_key)
model = genai.GenerativeModel('gemini-2.0-flash')

# App title and description
st.title("Research Paper Analyzer")
st.markdown("Upload a research paper PDF and get an AI-generated summary")

def extract_text_from_pdf(pdf_file):
    """Extract text from a PDF file"""
    pdf_reader = PyPDF2.PdfReader(pdf_file)
    text = ""
    
    # Extract text from each page
    for page_num in range(len(pdf_reader.pages)):
        page = pdf_reader.pages[page_num]
        text += page.extract_text()
    
    return text

def generate_summary(paper_text):
    """Generate a summary of the research paper using Gemini API"""
    # Limit text length to avoid exceeding API limits
    max_text_length = 30000  # Adjust based on model limitations
    truncated_text = paper_text[:max_text_length]
    
    prompt = f"""
    You are an academic research assistant. Analyze the following research paper and provide a comprehensive summary.
    
    Paper text:
    {truncated_text}
    
    Please provide:
    1. A concise summary of the paper's main findings and contributions (3-4 sentences)
    2. The key research question(s) addressed
    3. Methodology used
    4. Main results
    5. Limitations mentioned in the paper
    6. Potential applications or implications of the research
    
    Format your response with clear headings for each section.
    """
    
    response = model.generate_content(prompt)
    return response.text

# File uploader
uploaded_file = st.file_uploader("Upload Research Paper (PDF)", type="pdf")

if uploaded_file is not None:
    # Display file details
    file_details = {
        "Filename": uploaded_file.name,
        "File size": f"{uploaded_file.size / 1024:.2f} KB"
    }
    st.write("File Details:", file_details)
    
    # Add an analyze button
    if st.button("Analyze Paper"):
        with st.spinner("Processing PDF and generating summary..."):
            try:
                # Extract text from PDF
                paper_text = extract_text_from_pdf(io.BytesIO(uploaded_file.getvalue()))
                
                # Check if text was successfully extracted
                if paper_text.strip():
                    # Show a preview of the extracted text
                    with st.expander("Preview Extracted Text"):
                        st.text(paper_text[:1000] + "..." if len(paper_text) > 1000 else paper_text)
                    
                    # Generate summary
                    summary = generate_summary(paper_text)
                    
                    # Display summary
                    st.header("Research Paper Summary")
                    st.markdown(summary)
                    
                    # Add download button for the summary
                    st.download_button(
                        label="Download Summary",
                        data=summary,
                        file_name=f"{uploaded_file.name.split('.')[0]}_summary.txt",
                        mime="text/plain"
                    )
                else:
                    st.error("Could not extract text from the PDF. The file might be scanned or protected.")
            except Exception as e:
                st.error(f"An error occurred: {str(e)}")

# Example section
with st.expander("How to use this tool"):
    st.markdown("""
    ## How to Use the Research Paper Analyzer
    
    1. **Upload a PDF** of a research paper using the file uploader above
    2. **Click "Analyze Paper"** to process the document
    3. **Review the summary** generated by AI
    4. **Download the summary** for future reference
    
    This tool works best with:
    - Academic research papers
    - Scientific publications
    - Technical white papers
    - Conference proceedings
    
    Note: Very large PDFs may be truncated due to API limitations.
    """)

# Footer
st.markdown("---")
st.markdown("<div style='text-align: center;'>Made by Dhruv Mutha</div>", unsafe_allow_html=True)
